### ISSUE TITLE
#Question Can this library load class diagrame from xmi file 

### ISSUE THREAD

**Issue by badre429** [NMFCode/NMF#21]
i can't find any docs about this library i need to load class diagramme from xmi file

**Comment by georghinkel** [comment]
Most of the documentation is available in the form of papers listed here: https://sdqweb.ipd.kit.edu/publications/topics/nmf.html

In particular, there is a technical report that describes what NMF actually is: http://nbn-resolving.org/urn:nbn:de:swb:90-537082
Accompanied with this paper, you find a tutorial that spans quite a bunch of techniques available with NMF. Furthermore, there is a tutorial on YouTube: https://youtu.be/NIMYuwTltVs

**Comment by georghinkel** [comment]
To answer the question whether NMF can load class diagrams from XMI, it basically depends, namely it depends on whether you have a metamodel for class diagrams or whether you are willing to create one. If your class diagram is UML, then you should be able to use the UML metamodel used in Eclipse. You'd then have to generate the code for that and use that code to load instance documents from XMI, yes.
