### ISSUE TITLE
NMF-Basics 2.0.114 installation fails

### ISSUE THREAD

**Issue by Herbie60D** [NMFCode/NMF#35]
Hello Georg.
The NMF-Basics 2.0.114 installation currently does not work because it is missing the NMF-Repository 2.0.114 package.

**Comment by Herbie60D** [comment]
Also NMF-Synchronizations is still on version 2.0.113, but, since no other packages depend on it this maybe was intended.

**Comment by georghinkel** [comment]
Hi,

yes, the paths in the package specification were wrong (and unfortunately the CI did not fail because of this). It should be resolved with the latest commit that will be available in Nuget in about 15min.

Best,

Georg

**Comment by Herbie60D** [comment]
Thank you, but version  2.0.115 is not able to resolve the embedded model. I get the following error.

> Exception: The assembly NMF.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null declares a model but has no embedded resources. Did you forget to embed a model?
I've recreated the model with the Ecore2Code.exe, but I get the same error. When I switch to 2.0.113 (I have now a VS test installation) it works.

**Comment by georghinkel** [comment]
Yeah, I forgot to reference the models, I only referenced the code. I did not create .NET 4.5 versions of the tests because the .NET 4.5 code is 100% the same as the .NET Standard 2.0 version. I added the references and it should work now.

**Comment by Herbie60D** [comment]
Thank you! Now it works.
