### ISSUE TITLE
ecore field and enum the same name causes code generation problems

### ISSUE THREAD

**Issue by locsius** [NMFCode/NMF#37]
Hello -
I have run into this a bit while trying to load various ecore files.  Is there a nice way to alias the name somehow in your app?  

Thanks!
se

**Comment by georghinkel** [comment]
Hi,

no, so far aliases have not been implemented.

Best,

Georg

**Comment by georghinkel** [comment]
What kind of alias system would you expect? How would you like to specify the aliases?

**Comment by georghinkel** [comment]
#45 that has just been merged is a solution to your problem. Please reopen the issue if this is not the case.
