### ISSUE TITLE
MetaRepository can't resolve multiple namespaces with same interface

### ISSUE THREAD

**Issue by ChrisH07** [NMFCode/NMF#47]

**Comment by ChrisH07** [comment]
When resolving assemblies, the RegisterAssembly method in MetaRepository will throw an AmbiguousMatchException if multiple metamodels in separate namesapces contain the same interface.

**Comment by georghinkel** [comment]
Please confirm that the merged PR solved the problem

**Comment by ChrisH07** [comment]
Yes, this problem has been resolved.
