### ISSUE TITLE
Generated static Retrieve methods need namespace to qualify ClassInstance reference

### ISSUE THREAD

**Issue by ChrisH07** [NMFCode/NMF#51]
The generated static Retrieve...Attribute and Retrieve...Reference currently reference BaseType.ClassInstance which may not be a valid reference.  The full namespace for the BaseType is needed to resolve the class.

**Comment by georghinkel** [comment]
Please confirm that the merged PR solved the problem

**Comment by ChrisH07** [comment]
Yes, this problem has been resolved.

**Comment by ChrisH07** [comment]
Attached, [Models.zip](https://github.com/NMFCode/NMF/files/3461837/Models.zip), are 2 metamodels that recreate this issue at SHA 37a4c19d89c8c0e2ce0571cfc676b2a2c78aa326.  Code was generated with the following commands:
`-n ExampleA -f -o ./ModelA ModelA.nmf`
`-n ExampleB -f -o ./ModelB ModelB.nmf`

This was included in a class library with the following in AssemblyInfo.cs:
`[assembly: ModelMetadata("http://exampleA.com/ModelA/", "BlockSketch.MetaModels.ModelA.nmf")]
[assembly: ModelMetadata("http://exampleB.com/ModelB/", "BlockSketch.MetaModels.ModelB.nmf")]`

This class library was then referenced in a project that creates a model repo.  This caused the following exception to occur:

> System.Reflection.AmbiguousMatchException
  HResult=0x8000211D
  Message=Ambiguous match found.
  Source=mscorlib
  StackTrace:
   at System.RuntimeType.GetInterface(String fullname, Boolean ignoreCase)
   at System.Type.GetInterface(String name)
   at NMF.Models.Repository.MetaRepository.RegisterAssembly(Assembly assembly) in C:\Git\NMF\Models\Models\Repository\MetaRepository.cs:line 173

As a side note, I had trouble recreating this issue with a simple metamodel.  This issue occurred for me when both classes were called ModelElement, but I couldn't get this to build since the code generator didn't create the GetClass method.  This is may not be related, but the name is the same as an NMeta class and some of my metamodels and OMG metamodels have the same names as NMeta classes.  Additionally, if the class has no attributes or references then none of the interface methods are generated, but this is an unrealistic edge case.

**Comment by ChrisH07** [comment]
This issue can be reproduced from SHA 37a4c19d89c8c0e2ce0571cfc676b2a2c78aa326 with [kdm.txt](https://github.com/NMFCode/NMF/files/3461992/kdm.txt).  This is the OMG KDM metamodel converted to NMF. This metamodel was generated with:

`-n OMg -f -o ./OMG/KDM kdm.nmf`

This generated the following build errors:

> Error	CS1061	'Segment' does not contain a definition for 'Segment' and no accessible extension method 'Segment' accepting a first argument of type 'Segment' could be found (are you missing a using directive or an assembly reference?)
Error	CS1061	'Segment' does not contain a definition for 'Segment' and no accessible extension method 'Segment' accepting a first argument of type 'Segment' could be found (are you missing a using directive or an assembly reference?)
Error	CS1061	'Segment' does not contain a definition for '_segment' and no accessible extension method '_segment' accepting a first argument of type 'Segment' could be found (are you missing a using directive or an assembly reference?)
Error	CS1061	'Segment' does not contain a definition for '_segment' and no accessible extension method '_segment' accepting a first argument of type 'Segment' could be found (are you missing a using directive or an assembly reference?)
Error	CS0120	An object reference is required for the non-static field, method, or property 'KDMEntity.Track'
Error	CS0120	An object reference is required for the non-static field, method, or property 'KDMEntity.Track'

**Comment by georghinkel** [comment]
Ah, I recall that I have seen this error before. It is actually not that the problem that the type reference does not take part in the name conflict resolution system, it is rather that in C#, members take precedence over a type name. Therefore, the comiler resolve the name as a member whereas it is thought of being a type.

I put a comment why the fully qualified type name is needed. Further, I included the KDM metamodel (the original Ecore version) as a unit/integration test, so that should never fail again for a published package.
