### ISSUE TITLE
Ecore metamodel default values not taken into account (e.g. "unique=true")

### ISSUE THREAD

**Issue by ebousse** [NMFCode/NMF#9]
The default values of the attributes of the Ecore metamodel seem to not be taken into account (e.g. `unique=true`);

For example:
- In Eclipse, I create an Ecore model with a single class and with an _EReference_ with `unique=true`  using the built-in editor. In the serialized ecore file, it results in this line: `<eStructuralFeatures xsi:type="ecore:EReference" name="uniqueOrdered" upperBound="-1" eType="#//Test1"/>`
in which we do not see explicitly that `unique` is set to `true`, because `true` is the default value in the Ecore metamodel.
- When importing the Ecore file using NMeta, I can see in the resulting NMeta metamodel that `unique` is set to `null`, and not to `true`
- I generated the C# code for this imported metamodel. When using the generated code, the _EReference_ behaves as if `unique=false`, probably because it was `null `in the NMeta metamodel.

To bypass the problem, I have tried adding explicitly `unique = true` manually in the Ecore file I was importing, and then everything worked as expected.

Please find attached a small project with both Ecore files (one with `unique=true` implicit , and  another with `unique=true` explicit in the file), and a small test suite to show what I have tried, expected, and observed.

[TestUnique.zip](https://github.com/NMFCode/NMF/files/373667/TestUnique.zip)

**Comment by georghinkel** [comment]
The generation of default value literals was not working for nullable types. But as Ecore does not define a default value of the lower bound property, attributes like `unique` or `ordered` are rendered with type `Nullable<bool>`. This is now solved with the latest commit https://github.com/NMFCode/NMF/commit/393bce4ce68827bb3c28cefe2a8ba0a5bd843e4d. 

The metamodel you supplied generates the following backing fields for Test1:
```
        /// <summary>
        /// The backing field for the UniqueOrdered property
        /// </summary>
        private ObservableAssociationOrderedSet<ITest1> _uniqueOrdered;
        
        /// <summary>
        /// The backing field for the UniqueNonOrdered property
        /// </summary>
        private ObservableAssociationSet<ITest1> _uniqueNonOrdered;
        
        /// <summary>
        /// The backing field for the NonUniqueOrdered property
        /// </summary>
        private ObservableAssociationList<ITest1> _nonUniqueOrdered;
        
        /// <summary>
        /// The backing field for the NonUniqueNonOrdered property
        /// </summary>
        private ObservableAssociationList<ITest1> _nonUniqueNonOrdered;
        
        /// <summary>
        /// The backing field for the Opposite1Unique property
        /// </summary>
        private Test1Opposite1UniqueCollection _opposite1Unique;
        
        /// <summary>
        /// The backing field for the Opposite2Unique property
        /// </summary>
        private Test1Opposite2UniqueCollection _opposite2Unique;
        
        private static IClass _classInstance;
```
You can see that the references are now typed correctly with hash sets or ordered sets.

**Comment by ebousse** [comment]
Great! I've regenerated everything for my current project, and everything seems to work fine. Thanks a lot!
